<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DoomFire</RootNamespace>
    <AssemblyName>DoomFire</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fire/Shaders/*.frag" />
    <EmbeddedResource Include="Fire/Shaders/*.vert" />
  </ItemGroup>
</Project>
